backbone:
  _target_: modules.VitPoseVisualEncoder
  id: usyd-community/vitpose-plus-base
  hidden_states_layer: -2

visual_adapter:
  _target_: modules.TokenSampleTConvDapter
  hidden_size: 768
  target_hidden_size: 1024
  num_heads: 12
  num_layers: 1
  num_extra_queries: 8
  t_conv_type: 2
  mlp_depth: 2
  attn_drop: 0.0
  proj_drop: 0.0

visual_encoder_layer_scale: 1
connector_depth: 1
