opt:
  kwargs:
    opt: adamw
    lr: 1e-4

sched:
  name: cosine_with_min_lr
  kwargs:
    num_warmup_steps: 0
    num_training_steps: ${max_epochs}
    scheduler_specific_kwargs: { "min_lr": 1e-8, "num_cycles": 0.5 }
