type:
  _target_: model.mbart_slt.MBartSLTModel

backbone:
  _target_: model.mbart_slt.DinoV2Backbone
  id: facebook/dinov2-with-registers-base
  output_layer: -2

visual_adapter:
  _target_: model.mbart_slt.STCAdapter
  encoder_hidden_size: 768
  hidden_size: 1024
  downsample: [2, 2, 2]
  depth: 4
  mlp_depth: 2

visual_encoder_layer_scale: 1
# connector_depth: 1
