type:
  _target_: model.mbart_slt.MBartSLTModel

backbone:
  _target_: model.mbart_slt.DinoV2Backbone
  id: facebook/dinov2-with-registers-base
  output_layer: -2

visual_adapter:
  _target_: model.mbart_slt.TokenSampleAdapter
  hidden_size: 768
  target_hidden_size: 1024
  num_heads: 12
  num_layers: 1
  num_extra_queries: 8
  mlp_depth: 2
  attn_drop: 0.0
  proj_drop: 0.0

visual_encoder_layer_scale: 1
# connector_depth: 1
