defaults:
  - model: vlp
  - data: ph14t_*x224x224
  - engine: default
  # - override hydra/hydra_logging: null
  # - override hydra/job_logging: null
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
  job_logging:
    version: 1
    disable_existing_loggers: false
    root:
      handlers: []
