defaults:
  - modules: dinov2_base
  - data: ph14t_128x224x224
  - engine: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
