defaults:
  - model: vlp
  - data: ph14t_*x224x224
  - engine: default
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none
  - _self_

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
  # job_logging: null
  # hydra_logging: null
