defaults:
  - base_slt_quantized
  - override modules: dinov2_base
  - override data: ph14t_*x224x224
  - override engine: adam_cosine_anneal

data:
  batch_size: 8
  batch_size_val_test: 4

max_epochs: 200
devices: [2, 3, 4, 5, 6, 7]
precision: bf16-mixed

datamodule:
  num_workers: 8

engine:
  optimizer:
    lr: 1e-4
  lr_scheduler:
    instance:
      eta_min: 1e-8

visual_text_alignment_weight: 4.0
log_interval: 10

modules:
  visual_encoder_layer_scale: 1
